import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';
import { addMonths, differenceInMonths, isSameMonth, parseISO, startOfMonth, subMonths } from 'date-fns';
import { format } from 'date-fns';

export const dynamic = 'force-dynamic';

function getNextMonthlyPaymentDate(diaDePago: number | null): Date {
    const today = new Date();
    // Correct timezone shift for GMT-5 interpretation
    const localToday = new Date(today.getTime() - (today.getTimezoneOffset() * 60000));
    const currentMonth = localToday.getMonth();
    const currentYear = localToday.getFullYear();
    const day = diaDePago || 1;

    let targetDate = new Date(currentYear, currentMonth, day);
    if (localToday > targetDate) {
        targetDate = addMonths(targetDate, 1);
    }
    return targetDate;
}

function detectOwedPeriods(cliente: any, facturas: any[]) {
    if (!cliente.dia_de_pago && !cliente.Dia_De_Pago) return [];

    const isAnual = cliente.Plan && (cliente.Plan.toLowerCase().includes('anual') || cliente.Plan.toLowerCase().includes('anualidad'));
    if (isAnual) return []; // Anual billing is currently not auto-generated by month logic

    const today = new Date();
    const localToday = new Date(today.getTime() - (today.getTimezoneOffset() * 60000));
    const rawUltimoPago = cliente.fecha_ultimo_pago || cliente.Fecha_Ultimo_Pago;

    let startDate = rawUltimoPago ? parseISO(rawUltimoPago) : null;
    if (!startDate || isNaN(startDate.getTime())) {
        const createDate = cliente.created_at ? parseISO(cliente.created_at) : new Date();
        const startDay = cliente.dia_de_pago || cliente.Dia_De_Pago || 1;
        startDate = new Date(createDate.getFullYear(), createDate.getMonth(), startDay);
    }

    const diaCorte = cliente.dia_de_pago || cliente.Dia_De_Pago || 1;
    let targetStartDate = new Date(startDate.getFullYear(), startDate.getMonth(), diaCorte);

    if (startDate > targetStartDate) {
        targetStartDate = addMonths(targetStartDate, 1);
    }

    const startMonth = startOfMonth(targetStartDate);
    const currentMonth = startOfMonth(localToday);

    const periodosAbreviados = ['1 Mes', '2 Meses', '3 Meses', '4 Meses', '5+ Meses'];
    const periods = [];
    let monthsDiff = differenceInMonths(currentMonth, startMonth);

    if (localToday.getDate() >= diaCorte) {
        monthsDiff += 1;
    }

    for (let i = 0; i < monthsDiff; i++) {
        const periodDate = addMonths(targetStartDate, i);
        let label = format(periodDate, 'MMMM yyyy');

        const labelEspacios = {
            'January': 'Enero', 'February': 'Febrero', 'March': 'Marzo', 'April': 'Abril',
            'May': 'Mayo', 'June': 'Junio', 'July': 'Julio', 'August': 'Agosto',
            'September': 'Septiembre', 'October': 'Octubre', 'November': 'Noviembre', 'December': 'Diciembre'
        };
        for (const [eng, esp] of Object.entries(labelEspacios)) {
            label = label.replace(eng, esp);
        }

        const exactDateStr = format(periodDate, 'yyyy-MM-dd');
        const invoiceExists = facturas.some((f: any) => {
            if (!f.items || !Array.isArray(f.items)) return false;
            return f.items.some((item: any) => item.descripcion && item.descripcion.includes(label));
        });

        if (!invoiceExists) {
            periods.push({
                label,
                date: periodDate,
                monto: (cliente.tarifa || cliente.Tarifa || 0) * (cliente.cantidad_vehiculo || cliente.Cantidad_Vehiculo || 0),
                equipos: cliente.cantidad_vehiculo || cliente.Cantidad_Vehiculo || 0
            });
        }
    }

    return periods;
}

async function getNextInvoiceNumber() {
    const { data: facturas, error } = await supabase
        .from('Facturas')
        .select('numero_factura')
        .order('created_at', { ascending: false });

    if (error || !facturas || facturas.length === 0) return 'FACT-0001';

    let maxNum = 0;
    for (const fac of facturas) {
        if (!fac.numero_factura) continue;
        const match = fac.numero_factura.match(/FACT-(\d+)/);
        if (match && match[1]) {
            const num = parseInt(match[1], 10);
            if (num > maxNum) maxNum = num;
        }
    }

    return `FACT-${(maxNum + 1).toString().padStart(4, '0')}`;
}

export async function GET(request: Request) {
    try {
        const authHeader = request.headers.get('authorization');
        if (process.env.CRON_SECRET && authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
            return new NextResponse('Unauthorized', { status: 401 });
        }

        const { data: clients, error: clientsError } = await supabase
            .from('CLIENTES')
            .select(`
                *,
                Facturas (*)
            `);

        if (clientsError) throw clientsError;

        let invoicesGenerated = 0;
        let globalNextNumCounter = -1;

        for (const client of clients) {
            const periods = detectOwedPeriods(client, client.Facturas || []);

            if (periods.length > 0) {
                for (const item of periods) {
                    let nextNumStr = '';
                    if (globalNextNumCounter === -1) {
                        const baseNextNum = await getNextInvoiceNumber();
                        globalNextNumCounter = parseInt(baseNextNum.replace('FACT-', ''), 10);
                        nextNumStr = baseNextNum;
                    } else {
                        nextNumStr = `FACT-${globalNextNumCounter.toString().padStart(4, '0')}`;
                    }

                    const subtotal = item.monto;
                    const itbms = client.Requiere_Factura ? Number((subtotal * 0.07).toFixed(2)) : 0;
                    const total = Number((subtotal + itbms).toFixed(2));

                    const invoiceItems = [
                        {
                            descripcion: `Mensualidad de servicio de rastreo GPS ${item.label}`,
                            cantidad: item.equipos,
                            precio: client.Tarifa || 0,
                            total: subtotal
                        }
                    ];

                    const fechaEmision = new Date().toISOString().split('T')[0];
                    const fechaVencimiento = addMonths(new Date(), 1).toISOString().split('T')[0];

                    const { error: fError } = await supabase
                        .from('Facturas')
                        .insert([{
                            cliente_id: client.id,
                            numero_factura: `${nextNumStr} (${item.label})`,
                            monto_subtotal: subtotal,
                            monto_itbms: itbms,
                            monto_total: total,
                            items: invoiceItems,
                            fecha_emision: fechaEmision,
                            fecha_vencimiento: fechaVencimiento,
                            estado: 'pendiente',
                            es_electronica: false
                        }]);

                    if (fError) {
                        console.error(`Error saving invoice for client ${client.id}:`, fError);
                    } else {
                        invoicesGenerated++;
                        globalNextNumCounter++;
                    }
                }
            }
        }

        return NextResponse.json({
            success: true,
            message: `Automated billing check completed. Generated ${invoicesGenerated} missing invoices.`,
            invoicesGenerated
        });
    } catch (error: any) {
        console.error('Cron job error:', error);
        return NextResponse.json({ success: false, error: error.message }, { status: 500 });
    }
}
